version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: steam_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  streamlit_app:
    build: .
    container_name: steam_predictor_ui
    restart: always
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - .:/app

volumes:
  mongo_data:
